gitops:
  namespaceScoped: true

catalog:
  name: websphere-automation-catalog
  displayName: IBM WebSphere Automation Catalog
  image: icr.io/websphere-automation/cp/websphere-automation-operator-catalog:1.11.0-rc.1

subscription:
  wsaOperatorNamespace: ''
  channel: v1.10
  installPlanApproval: Automatic
  wsaInstanceNamespace: ''

operatorNamespace: ''

commonServicesNamespace: ''

licensingNamespace: ''

certManagerNamespace: ''

wsaHealth:
  spec:
    license:
      accept: ''

wsaSecure:
  spec:
    license:
      accept: ''      

wsa:
  spec:
    commonServices:
      registryNamespace: ''
    license:
      accept: ''